version: '3.7'

services:
  django-app-dev:
    build:
      context: .
      dockerfile: docker/server/dev.Dockerfile
    ports:
      - 8000:8000
    environment:
      - IN_DOCKER=True
    volumes:
      - static_volume:/usr/src/app/backend/staticfiles
  frontend-dev:
    build:
      context: .
      dockerfile: ./docker/client/dev.Dockerfile
    ports:
      - 3000:3000
    stdin_open: true
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/dev.Dockerfile
    ports: 
      - 8081:80
    volumes:
      - static_volume:/usr/src/app/backend/staticfiles
    depends_on: 
      - django-app-dev
      - frontend-dev

volumes:
  static_volume: